// Code generated by MockGen. DO NOT EDIT.
// Source: driver.go

// Package mock_host_query_reset is a generated GoMock package.
package mock_host_query_reset

import (
	reflect "reflect"

	driver "github.com/CannibalVox/VKng/core/driver"
	gomock "github.com/golang/mock/gomock"
)

// MockDriver is a mock of Driver interface.
type MockDriver struct {
	ctrl     *gomock.Controller
	recorder *MockDriverMockRecorder
}

// MockDriverMockRecorder is the mock recorder for MockDriver.
type MockDriverMockRecorder struct {
	mock *MockDriver
}

// NewMockDriver creates a new mock instance.
func NewMockDriver(ctrl *gomock.Controller) *MockDriver {
	mock := &MockDriver{ctrl: ctrl}
	mock.recorder = &MockDriverMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDriver) EXPECT() *MockDriverMockRecorder {
	return m.recorder
}

// VkResetQueryPool mocks base method.
func (m *MockDriver) VkResetQueryPool(device driver.VkDevice, queryPool driver.VkQueryPool, firstQuery, queryCount driver.Uint32) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "VkResetQueryPool", device, queryPool, firstQuery, queryCount)
}

// VkResetQueryPool indicates an expected call of VkResetQueryPool.
func (mr *MockDriverMockRecorder) VkResetQueryPool(device, queryPool, firstQuery, queryCount interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VkResetQueryPool", reflect.TypeOf((*MockDriver)(nil).VkResetQueryPool), device, queryPool, firstQuery, queryCount)
}
