// Code generated by MockGen. DO NOT EDIT.
// Source: extiface.go

// Package mock_host_query_reset is a generated GoMock package.
package mock_host_query_reset

import (
	reflect "reflect"

	core1_0 "github.com/CannibalVox/VKng/core/core1_0"
	gomock "github.com/golang/mock/gomock"
)

// MockExtension is a mock of Extension interface.
type MockExtension struct {
	ctrl     *gomock.Controller
	recorder *MockExtensionMockRecorder
}

// MockExtensionMockRecorder is the mock recorder for MockExtension.
type MockExtensionMockRecorder struct {
	mock *MockExtension
}

// NewMockExtension creates a new mock instance.
func NewMockExtension(ctrl *gomock.Controller) *MockExtension {
	mock := &MockExtension{ctrl: ctrl}
	mock.recorder = &MockExtensionMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockExtension) EXPECT() *MockExtensionMockRecorder {
	return m.recorder
}

// ResetQueryPool mocks base method.
func (m *MockExtension) ResetQueryPool(queryPool core1_0.QueryPool, firstQuery, queryCount int) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Reset", queryPool, firstQuery, queryCount)
}

// ResetQueryPool indicates an expected call of ResetQueryPool.
func (mr *MockExtensionMockRecorder) ResetQueryPool(queryPool, firstQuery, queryCount interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Reset", reflect.TypeOf((*MockExtension)(nil).ResetQueryPool), queryPool, firstQuery, queryCount)
}
