// Code generated by MockGen. DO NOT EDIT.
// Source: extension.go

// Package mock_debugutils is a generated GoMock package.
package mock_debugutils

import (
	reflect "reflect"

	common "github.com/CannibalVox/VKng/core/common"
	core1_0 "github.com/CannibalVox/VKng/core/core1_0"
	driver "github.com/CannibalVox/VKng/core/driver"
	ext_debug_utils "github.com/CannibalVox/VKng/extensions/ext_debug_utils"
	gomock "github.com/golang/mock/gomock"
)

// MockExtension is a mock of Extension interface.
type MockExtension struct {
	ctrl     *gomock.Controller
	recorder *MockExtensionMockRecorder
}

// MockExtensionMockRecorder is the mock recorder for MockExtension.
type MockExtensionMockRecorder struct {
	mock *MockExtension
}

// NewMockExtension creates a new mock instance.
func NewMockExtension(ctrl *gomock.Controller) *MockExtension {
	mock := &MockExtension{ctrl: ctrl}
	mock.recorder = &MockExtensionMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockExtension) EXPECT() *MockExtensionMockRecorder {
	return m.recorder
}

// CmdBeginLabel mocks base method.
func (m *MockExtension) CmdBeginDebugUtilsLabel(commandBuffer core1_0.CommandBuffer, label ext_debug_utils.DebugUtilsLabel) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CmdBeginDebugUtilsLabel", commandBuffer, label)
	ret0, _ := ret[0].(error)
	return ret0
}

// CmdBeginLabel indicates an expected call of CmdBeginLabel.
func (mr *MockExtensionMockRecorder) CmdBeginLabel(commandBuffer, label interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CmdBeginDebugUtilsLabel", reflect.TypeOf((*MockExtension)(nil).CmdBeginDebugUtilsLabel), commandBuffer, label)
}

// CmdEndLabel mocks base method.
func (m *MockExtension) CmdEndDebugUtilsLabel(commandBuffer core1_0.CommandBuffer) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "CmdEndDebugUtilsLabel", commandBuffer)
}

// CmdEndLabel indicates an expected call of CmdEndLabel.
func (mr *MockExtensionMockRecorder) CmdEndLabel(commandBuffer interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CmdEndDebugUtilsLabel", reflect.TypeOf((*MockExtension)(nil).CmdEndDebugUtilsLabel), commandBuffer)
}

// CmdInsertLabel mocks base method.
func (m *MockExtension) CmdInsertDebugUtilsLabel(commandBuffer core1_0.CommandBuffer, label ext_debug_utils.DebugUtilsLabel) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CmdInsertDebugUtilsLabel", commandBuffer, label)
	ret0, _ := ret[0].(error)
	return ret0
}

// CmdInsertLabel indicates an expected call of CmdInsertLabel.
func (mr *MockExtensionMockRecorder) CmdInsertLabel(commandBuffer, label interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CmdInsertDebugUtilsLabel", reflect.TypeOf((*MockExtension)(nil).CmdInsertDebugUtilsLabel), commandBuffer, label)
}

// CreateMessenger mocks base method.
func (m *MockExtension) CreateDebugUtilsMessenger(instance core1_0.Instance, allocation *driver.AllocationCallbacks, o ext_debug_utils.DebugUtilsMessengerCreateInfo) (ext_debug_utils.Messenger, common.VkResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateDebugUtilsMessenger", instance, allocation, o)
	ret0, _ := ret[0].(ext_debug_utils.Messenger)
	ret1, _ := ret[1].(common.VkResult)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// CreateMessenger indicates an expected call of CreateMessenger.
func (mr *MockExtensionMockRecorder) CreateMessenger(instance, allocation, o interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateDebugUtilsMessenger", reflect.TypeOf((*MockExtension)(nil).CreateDebugUtilsMessenger), instance, allocation, o)
}

// QueueBeginLabel mocks base method.
func (m *MockExtension) QueueBeginDebugUtilsLabel(queue core1_0.Queue, label ext_debug_utils.DebugUtilsLabel) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "QueueBeginDebugUtilsLabel", queue, label)
	ret0, _ := ret[0].(error)
	return ret0
}

// QueueBeginLabel indicates an expected call of QueueBeginLabel.
func (mr *MockExtensionMockRecorder) QueueBeginLabel(queue, label interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QueueBeginDebugUtilsLabel", reflect.TypeOf((*MockExtension)(nil).QueueBeginDebugUtilsLabel), queue, label)
}

// QueueEndLabel mocks base method.
func (m *MockExtension) QueueEndDebugUtilsLabel(queue core1_0.Queue) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "QueueEndDebugUtilsLabel", queue)
}

// QueueEndLabel indicates an expected call of QueueEndLabel.
func (mr *MockExtensionMockRecorder) QueueEndLabel(queue interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QueueEndDebugUtilsLabel", reflect.TypeOf((*MockExtension)(nil).QueueEndDebugUtilsLabel), queue)
}

// QueueInsertLabel mocks base method.
func (m *MockExtension) QueueInsertDebugUtilsLabel(queue core1_0.Queue, label ext_debug_utils.DebugUtilsLabel) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "QueueInsertDebugUtilsLabel", queue, label)
	ret0, _ := ret[0].(error)
	return ret0
}

// QueueInsertLabel indicates an expected call of QueueInsertLabel.
func (mr *MockExtensionMockRecorder) QueueInsertLabel(queue, label interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QueueInsertDebugUtilsLabel", reflect.TypeOf((*MockExtension)(nil).QueueInsertDebugUtilsLabel), queue, label)
}

// SetObjectName mocks base method.
func (m *MockExtension) SetDebugUtilsObjectName(instance core1_0.Device, name ext_debug_utils.DebugUtilsObjectNameInfo) (common.VkResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetDebugUtilsObjectName", instance, name)
	ret0, _ := ret[0].(common.VkResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetObjectName indicates an expected call of SetObjectName.
func (mr *MockExtensionMockRecorder) SetObjectName(instance, name interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetDebugUtilsObjectName", reflect.TypeOf((*MockExtension)(nil).SetDebugUtilsObjectName), instance, name)
}

// SetObjectTag mocks base method.
func (m *MockExtension) SetDebugUtilsObjectTag(instance core1_0.Device, tag ext_debug_utils.DebugUtilsObjectTagInfo) (common.VkResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetDebugUtilsObjectTag", instance, tag)
	ret0, _ := ret[0].(common.VkResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetObjectTag indicates an expected call of SetObjectTag.
func (mr *MockExtensionMockRecorder) SetObjectTag(instance, tag interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetDebugUtilsObjectTag", reflect.TypeOf((*MockExtension)(nil).SetDebugUtilsObjectTag), instance, tag)
}

// SubmitMessage mocks base method.
func (m *MockExtension) SubmitDebugUtilsMessage(instance core1_0.Instance, severity ext_debug_utils.MessageSeverities, types ext_debug_utils.MessageTypes, data ext_debug_utils.DebugUtilsMessengerCallbackData) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SubmitDebugUtilsMessage", instance, severity, types, data)
	ret0, _ := ret[0].(error)
	return ret0
}

// SubmitMessage indicates an expected call of SubmitMessage.
func (mr *MockExtensionMockRecorder) SubmitMessage(instance, severity, types, data interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SubmitDebugUtilsMessage", reflect.TypeOf((*MockExtension)(nil).SubmitDebugUtilsMessage), instance, severity, types, data)
}
